default['git']['config']['email'] = 'git@chrisforbes.dev'
default['git']['config']['name'] = 'Chris Forbes'
default['git']['username'] = 'kitforbes'
default['git']['timeout'] = 1200
default['git']['github_repositories'] = [
  '1PasswordPS',
  'automaton',
  'bootstrap',
  'chef_client_updater',
  'chef-repo',
  'computational-intelligence',
  'concurrent-and-parallel-systems',
  'Crawler',
  'docker-packer-ansible',
  'environments',
  'floppy',
  'games-engineering',
  'graphics-programming',
  'guide',
  'handmade',
  'honour',
  'infrastructure',
  'jfa',
  'jfa-assets',
  'kitforbes.github.io',
  'qa-mvc',
  'SalaryComparer',
  'scripts',
  'spark',
  'TerraFirma',
  'trap',
  'unite',
  'UtilitiesPS',
  'vscode-chef',
]
default['git']['gitlab_repositories'] = []

default['vscode']['extensions'] = [
  'bbenoist.vagrant',
  'burtlo.inspec',
  'codezombiech.gitignore',
  'DotJoshJohnson.xml',
  'EditorConfig.EditorConfig',
  'hashhar.gitattributes',
  'jirkafajfr.vscode-kitchen',
  'mauve.terraform',
  'ms-python.python',
  'ms-vscode.cpptools',
  'ms-vscode.csharp',
  'ms-vscode.PowerShell',
  'Pendrica.chef',
  'PeterJausovec.vscode-docker',
  'vscoss.vscode-ansible',
  'waderyan.gitblame',
  'wholroyd.jinja',
]
